-- 1. What is the total revenue generated by male vs. female customers?

SELECT 
    gender, SUM(purchase_amount)
FROM
    cusbehavior
GROUP BY gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,purchase_amount
FROM
    cusbehavior
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            cusbehavior);
            
-- 3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS highest_avg_rating
FROM
    cusbehavior
GROUP BY item_purchased
ORDER BY highest_avg_rating DESC
LIMIT 5; 

-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT 
    shipping_type, ROUND(AVG(purchase_amount), 2) avg_purchase
FROM
    cusbehavior
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(subscription_status) AS total_cus,
    ROUND(AVG(purchase_amount), 2) avg_spend,
    ROUND(SUM(purchase_amount), 2) total_spend
FROM
    cusbehavior
GROUP BY subscription_status
ORDER BY total_cus;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(purchase_amount),
            2) AS discount_rate
FROM
    cusbehavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH cte as (
	select *, case 
		when previous_purchases = 1 then "New"
		when previous_purchases <= 8 then "Returning" 
		else "Loyal" 
	end as cus_segment 
from cusbehavior)

Select cus_segment,count(cus_segment) as total_customers from cte group by cus_segment;

-- 8. What are the top 3 most purchased products within each category?

WITH cte AS (
SELECT
	item_purchased,category,count(customer_id) AS total_orders,ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) DESC) AS item_rnk
FROM 
	cusbehavior 
GROUP BY 
	category,item_purchased)

SELECT 
    item_purchased, category, total_orders, item_rnk
FROM
    cte
WHERE
    item_rnk <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status, COUNT(customer_id) as number_of_buyers
FROM
    cusbehavior
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contribution of each age group?

SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    cusbehavior
GROUP BY age_group
ORDER BY total_revenue DESC;

